#+title: Unreal Engine Quick-Reference

* Installation
** Introduction

Follow the instruction here (Linux Quickstart):

https://docs.unrealengine.com/4.27/en-US/SharingAndReleasing/Linux/BeginnerLinuxDeveloper/SettingUpAnUnrealWorkflow/

On Linux, there is no precompiled binary - we have to clone the repo from github
and compile it ourselves.

Have to sign up for an account with Epic and then link the Epic account to your
github account in order to gain access.

** Install on Laptop (Asus Zenbook 13)

Unreal Engine version: 4.27
Status: WORKING (but quite laggy)

Compiled OK (took ALL DAY)

Installed proprietory graphics drivers (don't know whether it made a
difference).

Running the editor, always crashed at 80-something percent, until I discovered
some special command line options for my laptop graphics card:

: $ __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only ./UE4Editor

Found out about these options from this video ("Unreal Engine run on laptop with
MX nvidia optimus graphics vulkan prime offload rendering linux"):

https://youtu.be/xTTJZA9W6Hs

* Running on my Laptop (Asus Zenbook 13)

Opening the editor - need to use special command line options for laptop
graphics card:

: $ __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only ./UE4Editor

Once the editor is running, dial down settings as low as possible:
- Settings-->Scalability-->Engine Scalability Settings--> EVERYTHING TO LOW
- Settings-->Scalability-->Material Quality Level-->LOW

Now, I can run the game in the editor and it's fairly responsive.

* When Unreal Crashes
Crash reports are saved here:
- UnrealEngine/Engine/Saved/Crashes

* Running a Project
** Running Project Editor

Running project in the editor:

: $ UE4Editor ProjectName.uproject

... here it is with special command line args for my laptop...

: $ __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only ~/Software/UnrealEngine/Engine/Binaries/Linux/UE4Editor


Or just run the editor and then select project from recent projects, or browse for project location:

: $ UE4Editor

Running an uncooked game (run editor with -game flag):

: $ UE4Editor ProjectName.uproject -game

Run in a window (default is fullscreen):

: $ UE4Editor ProjectName.uproject -game -windowed -resx=600 -resy=400

Press ~ to bring up the console
- type "exit" to exit the game

** Running Uncooked Game

Run from same dir as Unreal Editor binary: ~/Software/UnrealEngine/Engine/Binaries/Linux/UE4Editor

: $ __NV_PRIME_RENDER_OFFLOAD=1 __VK_LAYER_NV_optimus=NVIDIA_only ./UE4Editor ~/Unreal_Projects/TestCPP/TestCPP.uproject -game -windowed -resx=600 -resy=400

* Editor Basics

Play (Alt) --> play game in editor

Launch --> launch current map on device
- starts VERY LENGTHY build process
- eventually launched in fullscreen window
- to exit, press ~ to bring up the console, then type "exit"

Content Browser
- Map files

* C++ and Blueprints

Unreal Blueprints is a visual programming system (nodes & wires).
