* INTRO
HTTP works as a request-response protocol between a client and server.

A web browser may be the client, and an application on a computer that hosts a web site may be the server.

Example: A client (browser) submits an HTTP request to the server; then the server returns a response to the client. The response contains status information about the request and may also contain the requested content.

* METHODS
GET and POST are the two most common HTTP Request Methods.

    GET - Requests data from a specified resource
    POST - Submits data to be processed to a specified resource

** The GET Method

Note that the query string (name/value pairs) is sent in the URL of a GET request:
/test/demo_form.php?name1=value1&name2=value2

Some other notes on GET requests:

    GET requests can be cached
    GET requests remain in the browser history
    GET requests can be bookmarked
    GET requests should never be used when dealing with sensitive data
    GET requests have length restrictions
    GET requests should be used only to retrieve data

** The POST Method

Note that the query string (name/value pairs) is sent in the HTTP message body of a POST request:
POST /test/demo_form.php HTTP/1.1
Host: w3schools.com
name1=value1&name2=value2

Some other notes on POST requests:

    POST requests are never cached
    POST requests do not remain in the browser history
    POST requests cannot be bookmarked
    POST requests have no restrictions on data length

* TESTING
The nc (or netcat) utility is used for just about anything under the sun
involving TCP, UDP, or UNIX-domain sockets.  It can open TCP connections, send
UDP packets, listen on arbitrary TCP and UDP ports, do port scan‐ ning, and deal
with both IPv4 and IPv6.  Unlike telnet(1), nc scripts nicely, and separates
error messages onto standard error instead of sending them to standard output,
as telnet(1) does with some.


OPTIONS is supposed to give us a list of methods supported by the web server,
but when I try it like this it just returns the entire web page code...


$ nc www.bsartprize.info 80
OPTIONS / HTTP/1.1
Host: www.bsartprize.info

<press ENTER twice to submit>
